color_range_list:
  black:
    max:
    - 0
    - 227
    - 255
    min:
    - 0
    - 0
    - 0
  blue:
    max:
    - 160
    - 130
    - 128
    min:
    - 50
    - 88
    - 48
  green:
    max:
    - 189
    - 113
    - 171
    min:
    - 0
    - 56
    - 126
  red:
    max:
    - 157
    - 255
    - 238
    min:
    - 18
    - 137
    - 116
  white:
    max:
    - 56
    - 255
    - 255
    min:
    - 0
    - 0
    - 128
